Pinout:
  # Please note that these are not PIN numbers, but GPIO numbers. See https://pinout.xyz/ for more information.
  encoder_a: 5
  encoder_b: 6
  encoder_button: 13
  tilt_switch: 19

System:
  pixel_rows: 32
  pixel_cols: 64
  brightness: 100

Pushbullet:
  enabled: true
  websocket_url: xxx

OWM:
  enabled: true
  token: xxx
  lat: 0.0
  lon: 0.0

Spotify:
  enabled: true
  client_id: xxx
  client_secret: xxx
  redirect_uri: xxx

Notion:
  enabled: true
  token_v2: xxx
  source: xxx

Youtube:
  enabled: true
  key: xxx

Gif Viewer:
  enabled: true
  location: /home/raspberry/Athunas/src/apps/res/gif/horizontal
