# ------------------ System Configuration ------------------

Pinout:
  # Please note that these are NOT PIN numbers, but GPIO numbers. See https://pinout.xyz/ for more information.
  encoder_clk: 5
  encoder_dt: 6
  encoder_sw: 13
  tilt_switch: 19

System:
  led_rows: 32
  led_cols: 64
  brightness: 100

# ------------------ Module Configuration ------------------

# -------------------- App Configuration -------------------

Spotify:
  enabled: true
  client_id:
  client_secret:
  redirect_uri:

Notion:
  enabled: true
  token_v2:
  source:

Youtube:
  enabled: true
  key:

GifViewer:
  enabled: true

Pushbullet:
  enabled: true
  websocket_url:

OWM:
  enabled: true
  token:
  lat:
  lon:
